baseURL = "https://azmanabdullah.github.io"
languageCode = "en-us"
title = "Azmanabdlh"
theme = "rocinante"
paginate = 3

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["post", "photos"]
  email = "azmanabdlh@yahoo.com"
  about = """
  Hai saya **Azman Abdullah** - Software Engineer \n
  *Azmanabdullah.github.io*, adalah blog pribadi milik Azman abdullah
  yang berisi opini, tutorial dan tempat nulis-nulis biar gak lupa.\n
  🇮🇩Eastern Indonesian

"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "#"
    [[params.links.link]]
      name = "Project"
      href = "https://github.com/azmanabdullah"
      new_tab = false
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]

    [[params.links.link]]
      name = "Github"
      href = "https://github.com/azmanabdullah"
      new_tab = true
    [[params.links.link]]
      name = "Facebook"
      href = "https://mastodon.social/"
      new_tab = true
    [[params.links.link]]
      name = "WhatsApp"
      href = "#"
      new_tab = true
    [[params.links.link]]
      name = "Linkedin"
      href = "#"
      new_tab = true
